// src/h12_mbxb/h12_mbxb.dto.ts
export class CreateH12_mbxbDto {
  mblx: number;
  mbid: string;
  mxxh: number;
  xmid?: string;
  xmmc?: string;
  jfyl?: number;
  sjyl?: number;
  syffid?: string;
  syplid?: string;
  xmgg?: string;
  xmdw?: string;
  xmdj?: number;
  typbz?: string;
  tcbz?: number;
  scdh?: string;
  fylbid?: string;
  sfje?: number;
  sfbz?: number;
  fybz?: string;
  bzxx?: string;
  zflx?: string;
  xmzl?: number;
  cjid?: string;
  scph?: string;
  pfjg?: number;
  szbz?: number;
  sjyl1?: string;
  mrcs?: number;
  bz1?: string;
  bz2?: string;
  jldw?: string;
  gsid?: string;
  ypfl?: string;
  dwjb?: number;
  kyfs?: number;
  yzzh?: number;
  yzmxxh?: number;
  qt1?: string;
  ltbz?: string;
}

export class UpdateH12_mbxbDto {
  xmid?: string;
  xmmc?: string;
  jfyl?: number;
  sjyl?: number;
  syffid?: string;
  syplid?: string;
  xmgg?: string;
  xmdw?: string;
  xmdj?: number;
  typbz?: string;
  tcbz?: number;
  scdh?: string;
  fylbid?: string;
  sfje?: number;
  sfbz?: number;
  fybz?: string;
  bzxx?: string;
  zflx?: string;
  xmzl?: number;
  cjid?: string;
  scph?: string;
  pfjg?: number;
  szbz?: number;
  sjyl1?: string;
  mrcs?: number;
  bz1?: string;
  bz2?: string;
  jldw?: string;
  gsid?: string;
  ypfl?: string;
  dwjb?: number;
  kyfs?: number;
  yzzh?: number;
  yzmxxh?: number;
  qt1?: string;
  ltbz?: string;
}

export class H12_mbxbResponseDto {
  mblx: number;
  mbid: string;
  mxxh: number;
  xmid: string | null;
  xmmc: string | null;
  jfyl: number | null;
  sjyl: number | null;
  syffid: string | null;
  syplid: string | null;
  xmgg: string | null;
  xmdw: string | null;
  xmdj: number | null;
  typbz: string | null;
  tcbz: number | null;
  scdh: string | null;
  fylbid: string | null;
  sfje: number | null;
  sfbz: number | null;
  fybz: string | null;
  bzxx: string | null;
  zflx: string | null;
  xmzl: number | null;
  cjid: string | null;
  scph: string | null;
  pfjg: number | null;
  szbz: number | null;
  sjyl1: string | null;
  mrcs: number | null;
  bz1: string | null;
  bz2: string | null;
  jldw: string | null;
  gsid: string | null;
  ypfl: string | null;
  dwjb: number | null;
  kyfs: number | null;
  yzzh: number | null;
  yzmxxh: number | null;
  qt1: string | null;
  ltbz: string | null;
}
